version: '3'

services:
  mongo:
    container_name: mongo-dev
    image: mongo:4.0.21
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: nodepractice
    volumes:
      - ./docker-volumes/mongodb/data:/data/db
      - ./docker-volumes/mongodb/config-data:/data/configdb

  mongo-express:
    container_name: mongo-express-dev
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
